export const GET_IMAGES_REQUEST = 'GET_IMAGES_REQUEST';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_FAIL = 'GET_IMAGES_FAIL';

export const CREATE_IMAGE_REQUEST = 'CREATE_IMAGE_REQUEST';
export const CREATE_IMAGE_SUCCESS = 'CREATE_IMAGE_SUCCESS';
export const CREATE_IMAGE_FAIL = 'CREATE_IMAGE_FAIL';
export const CREATE_IMAGE_RESET = 'CREATE_IMAGE_RESET';

export const IMAGE_DETAILS_REQUEST = 'IMAGE_DETAILS_REQUEST';
export const IMAGE_DETAILS_SUCCESS = 'IMAGE_DETAILS_SUCCESS';
export const IMAGE_DETAILS_FAIL = 'IMAGE_DETAILS_FAIL';

export const UPDATE_IMAGE_REQUEST = 'UPDATE_IMAGE_REQUEST';
export const UPDATE_IMAGE_SUCCESS = 'UPDATE_IMAGE_SUCCESS';
export const UPDATE_IMAGE_FAIL = 'UPDATE_IMAGE_FAIL';
export const UPDATE_IMAGE_RESET = 'UPDATE_IMAGE_RESET';

export const DELETE_IMAGE_REQUEST = 'DELETE_IMAGE_REQUEST';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_FAIL = 'DELETE_IMAGE_FAIL';